CREATE DATABASE yeticafe
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
id_users INT NOT NULL,
id_bid INT NOT NULL,
create_lot INT NOT NULL,
dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email CHAR(126) NOT NULL UNIQUE,
name_user CHAR(126) NOT NULL UNIQUE,
password CHAR(64) NOT NULL,
contact CHAR(255) NOT NULL
);
CREATE TABLE categories(
id INT AUTO_INCREMENT PRIMARY KEY,
id_lot INT NOT NULL,
simbol CHAR NOT NULL UNIQUE,
name CHAR NOT NULL UNIQUE
);

CREATE TABLE lot(
id INT AUTO_INCREMENT PRIMARY KEY,
id_users INT NOT NULL,
winner INT,
id_cat INT NOT NULL,
dt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
title CHAR NOT NULL,
description TEXT,
link TEXT,
start_price DECIMAL NOT NULL,
dt_end DATE NOT NULL,
step_bid DECIMAL NOT NULL
);
CREATE TABLE bid(
id INT AUTO_INCREMENT PRIMARY KEY,
id_users INT NOT NULL,
id_lot INT NOT NULL,
dt_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
bid DECIMAL,
);
